### ISSUE TITLE
Willing to try on a DR-HAF003S

### ISSUE THREAD

**Issue by ERisEPR** [ouaibe/dreo-cloudcutter#2]
I have a DR-HAF003S and would be willing to try this on the fan while it is still in warranty :) But i am a complete noob would need guidance!

**Comment by ouaibe** [comment]
I applaud your audacity but I'm afraid I can't provide much more guidance than what's in the guide at the moment. Also, there's no indication whatsoever that your fan includes the same chip, and that the offsets in the YAML file wouldn't brick it, and so it would be necessary to do a firmware dump via soldered cables on your PCB _prior_ to doing any flashing (nobody has the stock firmware for that fan).

**Comment by SoCuul** [comment]
If I were to dump the firmware of my dreo fan (model DR-HPF008S), would you be able to assist further? Extremely impressed with this whole writeup, especially after how disappointed I was finding out it had no local control mechanism (even through HomeKit/Matter).

**Comment by ouaibe** [comment]
Please don't comment on old closed issues for a different fan/suggestion, do create new ones instead as I have a harder time seeing notifications on older posts. 

WRT the dump, the LibreTiny community has a place to collect them and might find it useful (via Discord), but I can't do much with them (except reverse for fun) as you need a working fan to analyze the communications protocol between the BK7231 and the MCU and re-implement it in ESPHome.

The model I "cloudcut" did have a specific protocol to select fan options (oscillation, speed, mode, etc.) and every fan model is likely going to be different because they have different options and maybe even a different MCU.

Unfortunately there's no "shortcut" here, it's either the full adventure or no cloudcutting 🫤
